[tool.poetry]
name = "py_terraform"
version = "0.1.0"
description = "Python wrapper for Terraform"
authors = ["Josh Wycuff <Joshua.Wycuff@turner.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6,<4"
terraform_install = {path = "../terraform_install", develop = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
