name: publish

jobs:
  terraform_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: pip install poetry==1.1.12
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-publish
      - name: Publish
        env:
          POETRY_PYPI_USERNAME: __token__
          POETRY_PYPI_PASSWORD: ${{ secrets.PIPY_API_TOKEN_TERRAFORM_VERSION }}
        working-directory: packages/terraform_version
        run: python internal/versions.py
